resources:
  pipelines:
    - pipeline: build
      source: 'aapp_app_mobile [build]'
      trigger:
        branches:
          include:
            - main

pool:
  name: Selfhosted Azure Devops Agents

parameters:
  - name: TEST_SUITE_ID
    displayName: 'Existing Test Suite ID (optional)'
    type: string
    default: ' '
  - name: IOS_APP_ID
    displayName: 'Existing iOS App ID (optional)'
    type: string
    default: ' '

variables:
  - group: aapp_testing_functional

steps:
  - task: ArchiveFiles@2
    condition: ${{ eq(parameters.TEST_SUITE_ID, ' ') }}
    inputs:
      rootFolderOrFile: '.maestro'
      includeRootFolder: true
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/maestro-tests.zip'
      replaceExistingArchive: true
    displayName: 'Create ZIP-file of Maestro tests'

  - download: build
    condition: ${{ eq(parameters.IOS_APP_ID, ' ') }}
    artifact: 'ios-build'
    displayName: 'Download app build files'

  - powershell: |
      $authString = "$(BROWSERSTACK_USERNAME)`:$(BROWSERSTACK_ACCESS_KEY)"
      $auth = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes($authString))
      Write-Host "##vso[task.setvariable variable=AUTH_HASH]$auth"
    displayName: 'Create BrowserStack Auth Hash'

  - powershell: |
      if ("${{ parameters.TEST_SUITE_ID }}" -ne " ") {
          Write-Host "TEST_SUITE_ID is pre-filled: ${{ parameters.TEST_SUITE_ID }}"
          Write-Host "##vso[task.setvariable variable=TEST_SUITE_ID]${{ parameters.TEST_SUITE_ID }}"
          exit 0
      }

      $headers = @{
          Authorization = "Basic $(AUTH_HASH)"
      }
      $form = @{
          custom_id = "ParkingStartSessionFlow"
          file = Get-Item "$(Build.ArtifactStagingDirectory)/maestro-tests.zip"
      }
      $testSuiteResponse = Invoke-RestMethod -Uri "https://api-cloud.browserstack.com/app-automate/maestro/v2/test-suite" `
          -Method POST `
          -Headers $headers `
          -Form $form

      Write-Host "Test Suite ID: $($testSuiteResponse.test_suite_id)"
      Write-Host "##vso[task.setvariable variable=TEST_SUITE_ID]$($testSuiteResponse.test_suite_id)"
    displayName: 'Upload Maestro tests to BrowserStack'

  - powershell: |
      if ("${{ parameters.IOS_APP_ID }}" -ne " ") {
          Write-Host "IOS_APP_ID is pre-filled: ${{ parameters.IOS_APP_ID }}"
          Write-Host "##vso[task.setvariable variable=IOS_APP_ID]${{ parameters.IOS_APP_ID }}"
          exit 0
      }

      $appFile = Get-ChildItem "$(Pipeline.Workspace)/build/ios-build/ios/builds" -Name "AmsterdamTest.ipa" | Select-Object -First 1
      if (-not $appFile) {
          Write-Host "##vso[task.logissue type=error]No AmsterdamTest.ipa file found"
          exit 1
      }

      $headers = @{
          Authorization = "Basic $(AUTH_HASH)"
      }
      $form = @{
          custom_id = "AmsterdamAppTest"
          file = Get-Item "$(Pipeline.Workspace)/build/ios-build/ios/builds/AmsterdamTest.ipa"
      }
      $appResponse = Invoke-RestMethod -Uri "https://api-cloud.browserstack.com/app-automate/maestro/v2/app" `
          -Method POST `
          -Headers $headers `
          -Form $form

      Write-Host "App ID: $($appResponse.app_id)"
      Write-Host "##vso[task.setvariable variable=IOS_APP_ID]$($appResponse.app_id)"
    displayName: 'Upload App to BrowserStack'

  - powershell: |
      $buildBody = @{
          app = "bs://$(IOS_APP_ID)"
          testSuite = "bs://$(TEST_SUITE_ID)"
          project = "Amsterdam App Maestro Tests"
          devices = @("iPhone 15-17.0")
          networkLogs = $false
          deviceLogs = $true
          execute = @("ParkingStartKraskaartSession.yaml")
      } | ConvertTo-Json -Depth 10
      $headers = @{
          Authorization = "Basic $(AUTH_HASH)"
          "Content-Type" = "application/json"
      }
      $buildResponse = Invoke-RestMethod -Uri "https://api-cloud.browserstack.com/app-automate/maestro/v2/ios/build" `
          -Method POST `
          -Headers $headers `
          -Body $buildBody

      Write-Host "Build ID: $($buildResponse.build_id)"
      Write-Host "##vso[task.setvariable variable=IOS_BUILD_ID]$($buildResponse.build_id)"
    displayName: 'Run Maestro Tests on iOS via BrowserStack'

  - powershell: |
      $buildId = "$(IOS_BUILD_ID)"
      $url = "https://api-cloud.browserstack.com/app-automate/maestro/v2/builds/$buildId"

      Write-Host "Build status URL: $url"

      $headers = @{
          Authorization = "Basic $(AUTH_HASH)"
      }
      $status = "running"
      $attempt = 0
      $maxAttempts = 60  # Wait up to 10 minutes (60 * 10s)
      $waitSeconds = 10

      Write-Host "Polling BrowserStack build status for build ID: $buildId"

      while ($status -eq "running" -and $attempt -lt $maxAttempts) {
          $response = Invoke-RestMethod -Uri $url -Headers $headers
          $status = $response.status
          Write-Host "Attempt $($attempt + 1): Status = $status"
          if ($status -eq "running") {
              Start-Sleep -Seconds $waitSeconds
              $attempt++
          }
      }

      if ($status -eq "running") {
          Write-Host "##vso[task.logissue type=error]Timed out waiting for build to finish."
          exit 1
      }

      Write-Host "Final build status: $status"
      Write-Host "View build result in BrowserStack: https://app-automate.browserstack.com/dashboard/v2/builds/$buildId"

      Write-Host "Full response:"
      $response | ConvertTo-Json -Depth 10

      if ($status -ne "passed") {
          Write-Host "##vso[task.logissue type=error]Build did not pass. Status: $status"
          exit 1
      }

    displayName: 'Wait for BrowserStack Build and Show Result'
