trigger:
- main

parameters:
  - name: androidAppId
    displayName: 'Existing Android App ID (optional)'
    type: string
    default: ' '
  - name: testSuiteId
    displayName: 'Existing Test Suite ID (optional)'
    type: string
    default: ' '

resources:
  pipelines:
    - pipeline: build
      source: 'aapp_app_mobile [build]'
      trigger:
        branches:
          include:
            - main

schedules:
  - cron: "0 22 * * *"   # every night
    displayName: Scheduled E2E Test
    branches:
      include:
        - main
    always: true  # run even if no recent changes

variables:
  - group: aapp_testing_e2e

pool:
      vmImage: 'macOS-15'

steps:
- template: templates/shared.yml
  parameters:
    appId: ${{ parameters.androidAppId }}
    testSuiteId: ${{ parameters.testSuiteId }}
    buildArtifact: 'android-build'
    appFileName: 'android/app/build/outputs/apk/dev/release/app-dev-release.apk'
    platform: 'android'
    device: 'Google Pixel 8 Pro-14.0'
    buildApiUrl: 'https://api-cloud.browserstack.com/app-automate/maestro/v2/android/build'
